declare module '@editorjs/paragraph'
declare module '@editorjs/header'
declare module '@editorjs/code'
declare module '@editorjs/list'
// declare module '@editorjs/nested-list'
// declare module '@editorjs/checklist'
// declare module '@editorjs/image'
declare module '@editorjs/simple-image'
declare module '@editorjs/link'
declare module '@calumk/editorjs-codeflask'
declare module '@editorjs/quote'
declare module '@calumk/editorjs-nested-checklist'